name: Scheduled task that sync mastodon to twitter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: install dependencies and run script
        env:
            CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
            CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            EMAIL: ${{ secrets.EMAIL }}
            NAME: ${{ secrets.NAME }}
            USER_ID : ${{ secrets.USER_ID }}
            INSTANCE_URL : ${{ secrets.INSTANCE_URL }}
        
        run: 
            pip install bs4 tweepy requests

            python3 ./mast2tw.py
          

      - name: Commit 
        run: |
            git add .
            git config --global user.name ${{ secrets.NAME }} 
            git config --global user.email ${{ secrets.EMAIL }}
            git commit -m "Added"

      - name: Push changes
            
        uses: ad-m/github-push-action@master
           
        with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: ${{ github.ref }}
            

    