name: Scheduled task that sync mastodon to twitter

on:
  push:
    branches:
      - main

jobs:
  push-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: install dependencies and run script
        run: |
            pip install bs4 tweepy re
            python3 ./mast2tw.py
          

      - name: Commit and Push
        run: |
          git config --global user.name ${{ secrets.NAME }} 
          git config --global user.email ${{ secrets.EMAIL }}
          git add sample.txt
          git commit -m "Add sample.txt"
          git push
