name: Scheduled task that sync mastodon to twitter

on:
  push:
    branches:
      - main

jobs:
  push-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: install dependencies and run script
        env:
            CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
            CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            EMAIL: ${{ secrets.EMAIL }}
            NAME: ${{ secrets.NAME }}
            USER_ID : ${{ secrets.USER_ID }}
            INSTANCE_URL : ${{ secrets.INSTANCE_URL }}
        
        run: 
            pip install bs4 tweepy requests
             
            python3 ./mast2tw.py
          

      - name: Commit and Push
        run: |
          git config --global user.name ${{ secrets.NAME }} 
          git config --global user.email ${{ secrets.EMAIL }}
          git add sample.txt
          git commit -m "Add sample.txt"
          git push
